### ISSUE TITLE
Multiple classes

### ISSUE THREAD

**Issue by extsoft** [akdcstar/ProjectComments#1]
There are two training in the different room. The first trainer teaches how to use git. The second one demonstrates how to bake a cake. Second room can have only 6 people at the same time while the first one is unlimited. 

Some implementation details: 
- `learn` and `teach` methods has to accept a `subject` as an argument
- If there is no space in the room, proper message is displayed when a room tries to accept the new student.  We don’t learn a student if it is not in the room.

**Comment by akdcstar** [comment]
@extsoft Please, take a look

**Comment by extsoft** [comment]
@akdcstar please work on the issues above.

**Comment by extsoft** [comment]
@akdcstar close as everything is done
