### ISSUE TITLE
Automate test #1 for Comments app

### ISSUE THREAD

**Issue by akdcstar** [akdcstar/ProjectComments#13]
Implement automated test case for Comments app.

Test #1 from https://docs.google.com/spreadsheets/d/1A3_5XFjxRlkfuSTgRIa81SMhW56siWPfEfo-_7YgLPQ/edit#gid=0.

Пользователь может создать  новый  комментарий при заполнении всех обязательных полей

**Comment by extsoft** [comment]
@akdcstar great job.
