### ISSUE TITLE
Remove unused list of rooms

### ISSUE THREAD

**Issue by extsoft** [akdcstar/ProjectComments#4]
https://github.com/akdcstar/ProjectComments/blob/ee5242286cb1aa2037d6beccf5bc27593fbcbec6/src/main/java/net/comments/sample/App.java#L28

Related to #1

**Comment by akdcstar** [comment]
@extsoft Do you have any questions related to #4 and #5? They was implemented yesterday.

**Comment by extsoft** [comment]
@akdcstar No, I don't. Next time pls implement and discuss each issue separately.
