### ISSUE TITLE
Add more behavior for Subject

### ISSUE THREAD

**Issue by extsoft** [akdcstar/ProjectComments#6]
https://github.com/akdcstar/ProjectComments/blob/ee5242286cb1aa2037d6beccf5bc27593fbcbec6/src/main/java/net/comments/sample/Subject.java#L3

Think about a subject as about separate creature. The subject can `readBy` a teacher and `learnBy` a student.

Related to #1

**Comment by akdcstar** [comment]
Can't understand what should methods `readBy` and `learnBy` do.

**Comment by extsoft** [comment]
@akdcstar I have been explained during the lesson. Do you still have the questions?
