### ISSUE TITLE
Limit the number of persons in the  CookingRoom

### ISSUE THREAD

**Issue by extsoft** [akdcstar/ProjectComments#7]
If there is no space in the room, proper message is displayed when a room tries to accept the new student. We don’t learn a student if it is not in the room.

The part of #1

**Comment by akdcstar** [comment]
In my case CookingRoom is unlimited and TrainingRoom is limited by 3 places.

**Comment by extsoft** [comment]
@akdcstar I don't see any place where we say some people that a room is full.
